# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:42
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import migrations, models
from ..models import Posting


class Migration(migrations.Migration):

    # def load_user(apps, schema_editor):
    #     u = User.objects.create_user('ryansemmler', "semmra7@gmail.com", "PASSWORD")
    #     u.save()

    # def load_listing(apps, schema_editor):
    #     l = Posting(title="Chicken Pizza", description="It's a goddamn chicken pizza", image="https://www.landolakes.com/RecipeManagementSystem/media/Recipe-Media-Files/Recipes/Retail/DesktopImages/15684.jpg?ext=.jpg")
    #     l.city = "Raleigh"
    #     l.user =

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.RunPython(load_user),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=1500)),
                ('image', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
