# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:47
from __future__ import unicode_literals
from ..models import Category
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20170324_1439'),
    ]

    operations = [
        # migrations.RunPython(load_categories),
        migrations.AlterField(
            model_name='posting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cl_app.Category'),
        ),
    ]
