# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:02
from __future__ import unicode_literals
from ..models import Category
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def load_categories(apps, schema_editor):
        c = Category(name="For Sale")
        c.save()

    dependencies = [
        ('cl_app', '0003_auto_20170324_1447'),
    ]

    operations = [
        migrations.RunPython(load_categories),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cl_app.Category'),
        ),
    ]
