# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cl_app', '0004_auto_20170324_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
